// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsa63KJVIqvY4a3dWm3EJwsYRr45tJyy4',
    appId: '1:718171718568:web:7b8b00249ed26922a4939d',
    messagingSenderId: '718171718568',
    projectId: 'sendme-498a9',
    authDomain: 'sendme-498a9.firebaseapp.com',
    databaseURL: 'https://sendme-498a9-default-rtdb.firebaseio.com',
    storageBucket: 'sendme-498a9.firebasestorage.app',
    measurementId: 'G-EB2QGFPX7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmHyD_sMGZJsvU6SUmSPkaIaU46fT8XwE',
    appId: '1:718171718568:android:70a14e26dcba2380a4939d',
    messagingSenderId: '718171718568',
    projectId: 'sendme-498a9',
    databaseURL: 'https://sendme-498a9-default-rtdb.firebaseio.com',
    storageBucket: 'sendme-498a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdL_J_IAHSt934VbRazbMnWMLjQGZNL0Y',
    appId: '1:718171718568:ios:b339b197b51ef0b4a4939d',
    messagingSenderId: '718171718568',
    projectId: 'sendme-498a9',
    databaseURL: 'https://sendme-498a9-default-rtdb.firebaseio.com',
    storageBucket: 'sendme-498a9.firebasestorage.app',
    iosBundleId: 'com.example.healwiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdL_J_IAHSt934VbRazbMnWMLjQGZNL0Y',
    appId: '1:718171718568:ios:b339b197b51ef0b4a4939d',
    messagingSenderId: '718171718568',
    projectId: 'sendme-498a9',
    databaseURL: 'https://sendme-498a9-default-rtdb.firebaseio.com',
    storageBucket: 'sendme-498a9.firebasestorage.app',
    iosBundleId: 'com.example.healwiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMduZ0gccWxbmOVP-b24K3CR9wRhNEXKo',
    appId: '1:718171718568:web:176cc6d566d9734ca4939d',
    messagingSenderId: '718171718568',
    projectId: 'sendme-498a9',
    authDomain: 'sendme-498a9.firebaseapp.com',
    databaseURL: 'https://sendme-498a9-default-rtdb.firebaseio.com',
    storageBucket: 'sendme-498a9.firebasestorage.app',
    measurementId: 'G-6L3SWR7N2L',
  );
}
